[variables]
NIXPACKS_NODE_VERSION = "20"
VITE_API_BASE = "https://api.ayosekolah.my.id"
VITE_API_TARGET = "https://api.ayosekolah.my.id"

[phases.install]
cmds = ["npm install --global pnpm@10.28.1", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "npx serve -s build -l 3000"
